version: '3.8'

services:
  # Virtual Node 4 (Simulated Worker Node on Laptop B)
  node-4:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: node-4
    hostname: node-4
    environment:
      - BACKEND_URL=http://192.168.66.107:8000
      - REGISTRATION_TOKEN=clusterdash-worker-secret-token
      - HEARTBEAT_INTERVAL=5
      - NODE_ROLE=worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  # Virtual Node 5 (Simulated Worker Node on Laptop B)
  node-5:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: node-5
    hostname: node-5
    environment:
      - BACKEND_URL=http://192.168.66.107:8000
      - REGISTRATION_TOKEN=clusterdash-worker-secret-token
      - HEARTBEAT_INTERVAL=5
      - NODE_ROLE=worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  # Virtual Node 6 (Simulated Worker Node on Laptop B)
  node-6:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: node-6
    hostname: node-6
    environment:
      - BACKEND_URL=http://192.168.66.107:8000
      - REGISTRATION_TOKEN=clusterdash-worker-secret-token
      - HEARTBEAT_INTERVAL=5
      - NODE_ROLE=worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
